backend = "glx";
vsync = true;

shadow = true;
shadow-radius = 18;
shadow-offset-x = -8;
shadow-offset-y = -8;
shadow-opacity = 0.24;
shadow-exclude = [
  "class_g = 'Polybar'",
  "class_g = 'Rofi'",
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

fading = true;
fade-in-step = 0.045;
fade-out-step = 0.045;
fade-delta = 5;

inactive-opacity = 0.96;
active-opacity = 1.0;
frame-opacity = 1.0;
inactive-opacity-override = false;

corner-radius = 8;
rounded-corners-exclude = [
  "class_g = 'Polybar'",
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

blur: {
  method = "dual_kawase";
  strength = 8;
  background = true;
  background-frame = false;
  background-fixed = false;
}
blur-background-exclude = [
  "class_g = 'Polybar'",
  "window_type = 'dock'",
  "window_type = 'desktop'"
];
detect-rounded-corners = true;
detect-client-opacity = true;
use-damage = true;
log-level = "warn";

opacity-rule = [
  "88:class_g = 'Alacritty'",
  "90:class_g = 'Rofi'",
  "98:class_g = 'Dunst'"
];
