skip_selection = true

[background]
path = "/usr/share/backgrounds/wallpapers/loginwallpaper.jpg"
fit = "Cover"

[GTK]
application_prefer_dark_theme = true
cursor_blink = false
font_name = "Inter 11"
icon_theme_name = "Adwaita"
theme_name = "Adwaita"

[appearance]
greeting_msg = ""

[widget.clock]
format = "<span font_family='Inter' size='64000' weight='800' foreground='#00fbfb'>%H:%M</span>\n<span font_family='Inter' size='20000' weight='600' foreground='#eabea0'>%A, %B %-d</span>"
resolution = "60s"
label_width = 450

[commands]
reboot = ["systemctl", "reboot"]
poweroff = ["systemctl", "poweroff"]