[background]
path = "/usr/share/backgrounds/arch-scripts/loginwallpaper.jpg"
fit = "Cover"

[GTK]
application_prefer_dark_theme = true
font_name = "monospace 11"

[commands]
reboot = ["loginctl", "reboot"]
poweroff = ["loginctl", "poweroff"]
