[background]
path = "/usr/share/backgrounds/wallpapers/loginwallpaper.jpg"
fit = "Cover"

[GTK]
application_prefer_dark_theme = true
font_name = "Inter 11"

[appearance]
greeting_msg = "Welcome back"

[widget.clock]
format = "%H:%M\n%A, %B %d"
resolution = "60s"
label_width = 520

[commands]
reboot = ["loginctl", "reboot"]
poweroff = ["loginctl", "poweroff"]
